### ISSUE TITLE
Could not run example_faces.m

### ISSUE THREAD

**Issue by vktt** [kyunghyuncho/deepmat#1]
Hi

It seems there is an issue in how you're choosing to visualize the training of GRBM. I encountered some problems running the above example.

Though the fix/workaround seems easy. I think you haven't fully modified the visualize_grbm.m file yet. A slight change in definition solves the problem.

 Errors were:

Error using visualize_grbm
Too many input arguments.

Error in rbm (line 560)
            R.debug.display_function (R.debug.display_fid, R, v0, v1, h0, h1, W_grad, vbias_grad,
            hbias_grad);

Error in train_rbm (line 49)
        R_out = rbm(R, patches);

Error in example_faces (line 46)
R = train_rbm (R, X);

**Comment by kyunghyuncho** [comment]
Thanks for reporting. This was caused by merging GRBM and RBM codes without considering how the merge affected visualization functions. This has been fixed and committed.
