### ISSUE TITLE
Small typo in mlp.m

### ISSUE THREAD

**Issue by vktt** [kyunghyuncho/deepmat#2]
line 23 is:     valid_targest = [];
should be:     valid_targets = [];
It is only an issue if less than 3 parameters are passed to the function (nargin<3)

Also, I have a question:

In default_mlp.m, why are you using binary input  and binary outputs?

```
% data type
M.data.binary = 1;
%M.data.binary = 0;

% output type
M.output.binary = 1;
```

Thanks,
Vikrant.

**Comment by kyunghyuncho** [comment]
1. Thanks for pointing it out. It's been now fixed. 
2. default_mlp.m: It's just a default value, and you can change it by simply setting M.data.binary or M.output.binary = 0. In fact, in the case of MLPs, the input type does not really matter at all, but the output type should be set accordingly depending on whether you're aiming to do classification (M.output.binary = 1) or regression (M.output.binary = 0)
