### ISSUE TITLE
error in line 49

### ISSUE THREAD

**Issue by subhaprakash0106** [kyunghyuncho/deepmat#4]
```
   could you check example mnist.m file. it's shows error in line 49
```

**Comment by kyunghyuncho** [comment]
What kind of error do you get?

**Comment by subhaprakash0106** [comment]
> > example_mnist
> > when i run above file, i get the following error.
> > Training RBM
> > Epoch 1/20: .# updates: 1
> > .# updates: 2
> > .# updates: 3
> > .# updates: 4
> > .# updates: 5
> > .# updates: 6
> > .# updates: 7
> > .# updates: 8
> > .# updates: 9
> > .# updates: 10
> > Error using visualize_rbm
> > Too many input arguments.

Error in rbm (line 562)
            R.debug.display_function (R.debug.display_fid, R, v0, v1, h0, h1, W_grad, vbias_grad, hbias_grad, sigma_grad);

Error in train_rbm (line 49)
        R_out = rbm(R, patches);

Error in example_mnist (line 44)
R = train_rbm (R, X);

**Comment by kyunghyuncho** [comment]
That's probably a bug with visualize_rbm.m. I will try to fix it soon, but meanwhile you can simply set R.debug.do_display to 0 (line 36 of example_mnist.m). Sorry about this.

**Comment by subhaprakash0106** [comment]
After changing that too, i am getting following error.

# updates: 9375

.# updates: 9376
.# updates: 9377
.# updates: 9378
.# updates: 9379
.# updates: 9380

Epoch 20/20 - recon_error: 13.159514 norms: 0.001624/8.022626/0.413834
Training is done after 85.074836 seconds
Training the classifier: Undefined function 'train' for input arguments of type 'double'.

Error in example_mnist (line 49)
model = train(X_labels, sparse(rbm_feature), '-s 0');

**Comment by kyunghyuncho** [comment]
That error is due to the lack of libsvm (or liblinear) in which 'train' function is defined.

**Comment by subhaprakash0106** [comment]
thanks cho.

**Comment by subhaprakash0106** [comment]
once i  fixed up the above error i got the following one..

Epoch 20/20 - recon_error: 13.835114 norms: 0.001624/8.122934/0.414755

Training is done after 83.799645 seconds
Training the classifier: Error: weight vector, label vector and instance matrix must be double
Done
Testing the classifier: model file should be a struct array
Done
Running AIS: 100.200.300.400.500.600.700.800.900.1000.1100.1200.1300.1400.1500.1600.1700.1800.1900.2000.2100.2200.2300.2400.2500.2600.2700.2800.2900.3000.3100.3200.3300.3400.3500.3600.3700.3800.3900.4000.4100.4200.4300.4400.4500.4600.4700.4800.4900.5000.5100.5200.5300.5400.5500.5600.5700.5800.5900.6000.6100.6200.6300.6400.6500.6600.6700.6800.6900.7000.7100.7200.7300.7400.7500.7600.7700.7800.7900.8000.8100.8200.8300.8400.8500.8600.8700.8800.8900.9000.9100.9200.9300.9400.9500.9600.9700.9800.9900.10000.Done
========================log P(train) = -534.031076
log P(test) = -534.191487
log P(rand) = -315.017961
========================Error using  \* 
Inner matrix dimensions must agree.

Error in rbm_sample (line 38)
            vh(:, n_visible + j) = sigmoid(vh \* R.W(:, n_visible + j) + R.hbias(j)) > rand(size(vh, 1), 1);

Error in example_mnist (line 76)
S = rbm_sample(binornd(1, 0.5, 10, size(X,2)), R, 30, 1000);

**Comment by kyunghyuncho** [comment]
- Error related to "Training the classifier: Error: weight vector, label vector and instance matrix must be double" and "Testing the classifier: model file should be a struct array" was due to the lack of casting rbm_feature into double when the model was trained on GPU using single-precision entry. This error has been fixed and pushed to the repository. Pull the latest version and try again.
- The error related to rbm_sample is due to some mix-up during my repository management. Apparently rbm_sample.m does not implement sampling from rbm but from fully connected boltzmann machine. This will be fixed soon, but meanwhile you can simply comment out lines 75 - 82.

**Comment by subhaprakash0106** [comment]
thanks..

**Comment by subhaprakash0106** [comment]
when i run example_faces.m file , i was getting this error. i have already run that one 2days ago, it was working fine.but now i am getting this error.can i get an idea why it occurs now.as you said before if i change debug.display  to 0,i ts fine..But i would like to know ,why it was working fine previously and why cant now?could you give some idea..

Epoch 1/100: .# updates: 1
.# updates: 2
.# updates: 3
.# updates: 4
.# updates: 5
Reference to a cleared variable v0.

Error in rbm (line 562)
            R.debug.display_function (R.debug.display_fid, R, v0, v1, h0, h1, W_grad, vbias_grad, hbias_grad, sigma_grad);

Error in train_rbm (line 49)
        R_out = rbm(R, patches);

Error in example_faces_3 (line 46)
R = train_rbm (R, X);

**Comment by kyunghyuncho** [comment]
That's again related to the display functionality I implemented a while ago. I cannot fix it soon as I'm not in good environment to debug and fix things in matlab at the moment. For now, you can simply disable do_display. I have pushed the code to by default not use do_display functionality. You can pull the latest version and retry.

**Comment by subhaprakash0106** [comment]
ok..thats fine.
