### ISSUE TITLE
Problems running example_mnist_dae.m

### ISSUE THREAD

**Issue by kkoro** [kyunghyuncho/deepmat#5]
Hi,
When I run this example, the call to predict on line 60 returns null values for [L accuracy] and I get the exit_with_help message from the predict function. The only change I made was to use liblinear-1.94 instead of liblinear-1.7.

The model that was trained in line 55 is:

model = 
    Parameters: 0
      nr_class: 10
    nr_feature: 500
          bias: -1
         Label: [10x1 double]
             w: [10x500 double]

**Comment by kyunghyuncho** [comment]
Hi,

I'm currently on my holidays. Can you check with liblinear-1.7 and see if
the same error happens?

**Comment by kkoro** [comment]
Thanks very much for the suggestion. It seems to work with liblinear-1.7, but not with the latest 1.94. I had some issues installing and compiling both liblinear 1.7 and 1.94 on my Mac (OS X 10.9.4 with Xcode 5.1.1). But in the end both versions seem to successfully run heart_scale_example.m (provided in liblinear). For some reason though your example_mnist_dae.m doesn't seem to work with ver 1.94.

I get the following output with version 1.7:
Testing the classifier: Accuracy = 94.46% (9446/10000)

**Comment by kyunghyuncho** [comment]
Hi, I just checked the latest version of liblinear (1.94) and it seems like they have changed the matlab interface since 1.7. I've fixed example_mnist_dae.m and example_mnist.m to work also with liblinear-1.94 now. Please, pull the latest version and use it.
